// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *input_size;
extern Fl_Value_Input *input_iterations;
extern Fl_Value_Input *input_rule;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_run;
#include <FL/Fl_Box.H>
extern Fl_Box *result;
int main();
void callback_run();
int* solve_rule(int rule);
int to_decimal(int bin);
void draw_image(Fl_Box* canvas, int size, int iterations,int rule);
#endif
