// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *input_width;
extern Fl_Value_Input *input_height;
#include "Imagebox.h"
extern Imagebox *result;
#include <FL/Fl_Choice.H>
extern Fl_Choice *menu_initial;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_prv;
extern Fl_Button *btn_nxt;
extern Fl_Button *btn_set;
extern imageStack* stack;
int main();
extern Fl_Menu_Item menu_menu_initial[];
#define empty (menu_menu_initial+0)
#define constant_ (menu_menu_initial+1)
#define glider (menu_menu_initial+2)
#define oscillator (menu_menu_initial+3)
#define random (menu_menu_initial+4)
void callback_next();
void callback_prev();
void callback_draw();
#endif
